' http://plantuml.sourceforge.net/sequence.html

@startuml sekvenssi2.png

title UISwing
autonumber
hide footbox

participant "main:VilleBasse" as main
participant "ui:UISwing" as ui
participant "engine:VilleBasseEngine" as vbe
participant "borderPanel:BorderPanel" as bp
participant "controlPanel:ControlPanel" as cp

== Käyttöliittymän alustus ==
activate main
main -> ui: initialize(args)
main -> ui: run()
activate ui
deactivate main

ui -> vbe: new VilleBasseEngine()
activate vbe
ui -> vbe: addGameStateEngineListener(this)
ui -> vbe: getBoard()
ui <- vbe: board:Board

ui -> bp: new BoardPanel(board)
activate bp
ui -> bp: addUserEventListener(this)
ui -> cp: new ControlPanel()
activate cp
ui -> cp: addUserEventListener(this)

ui -> vbe: addPlayers()
ui -> vbe: startGame()

== Toista ==
ui <- vbe: gse:GameStateEvent
ui -> bp: setUserEventListener()
ui <- bp: ue:UserEvent
ui -> vbe: tapahtumaan liittyvä toiminto

== kunnes pakka tyhjä ==
ui <- vbe: pakka tyhjä
deactivate vbe
deactivate bp
deactivate cp
deactivate ui

@enduml
